const serviceContent = [{
    name: "Auditing",
    content: "The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.",
    author: "Malini"
},{
    name: "IT Returns",
    content: "The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.",
    author: "Malini"
},{
    name: "Bank Statement",
    content: "The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.",
    author: "Malini"
},{
    name: "Internship and Certification",
    content: "The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.The refresh button is not really part of the component - I added that so you can see the spinner in action. The refresh button is not really part of the component - I added that so you can see the spinner in action.",
    author: "Malini"
}];

export default serviceContent;